# Site settings
title: World of Us
email: 
description: ""
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: World of Us
email: 
facebook_username: 
twitter_username: 
github_username: 
address:
  - line: 세븐스프링스목동41타워점
  - line: "서울특별시 양천구 목1동 917-9"
  # Feel free to add more lines here 
telephone: "02)2168-2511"
copyright: "nature Kim"


# API settings
google_api_key: AIzaSyAfr_s_0pfcs2gcpjyOMbqYNcdUvZN44g4

# Build settings
markdown: kramdown